/**
 * Pre-trained Environmental Baseline Parameters
 * Auto-generated by train_anomaly_model.py
 */

#ifndef BASELINE_PARAMS_H
#define BASELINE_PARAMS_H

static const float PRETRAINED_MEANS[] = {50.0168f, 0.0485f, 1013.2547f, 65.0828f, 27.9778f};
static const float PRETRAINED_STDS[]  = {2.9891f, 0.0474f, 1.4863f, 5.0169f, 2.4868f};
static const float PRETRAINED_MINS[]  = {40.2762f, 0.0000f, 1007.3664f, 46.8240f, 18.3591f};
static const float PRETRAINED_MAXS[]  = {61.7787f, 0.4013f, 1018.3934f, 87.3954f, 37.0284f};

#endif // BASELINE_PARAMS_H
