"""
Disaster Sentinel — TinyML Anomaly Model Trainer

Trains a lightweight statistical baseline model / autoencoder for ESP32 nodes.
Exports optimized C++ header file (baseline_params.h) for embedding directly into firmware.
"""

import os
import json
import numpy as np


def generate_synthetic_environmental_data(num_samples: int = 5000):
    """Generate normal baseline environmental data for training."""
    np.random.seed(42)
    
    # Flood Node channels
    water_level = np.random.normal(loc=50.0, scale=3.0, size=num_samples)
    rain_intensity = np.random.exponential(scale=0.05, size=num_samples)
    rain_intensity = np.clip(rain_intensity, 0, 1.0)
    pressure = np.random.normal(loc=1013.25, scale=1.5, size=num_samples)
    humidity = np.random.normal(loc=65.0, scale=5.0, size=num_samples)
    temperature = np.random.normal(loc=28.0, scale=2.5, size=num_samples)
    
    data = np.column_stack([water_level, rain_intensity, pressure, humidity, temperature])
    return data


def compute_baseline_params(data: np.ndarray):
    """Compute mean, std_dev, min, max for C++ header export."""
    means = np.mean(data, axis=0)
    stds = np.std(data, axis=0)
    mins = np.min(data, axis=0)
    maxs = np.max(data, axis=0)
    
    # Avoid zero std
    stds = np.where(stds < 1e-6, 1.0, stds)
    
    return {
        "means": means.tolist(),
        "stds": stds.tolist(),
        "mins": mins.tolist(),
        "maxs": maxs.tolist(),
    }


def export_cpp_header(params: dict, output_path: str):
    """Export parameters to C++ header file."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    means_str = ", ".join(f"{x:.4f}f" for x in params["means"])
    stds_str = ", ".join(f"{x:.4f}f" for x in params["stds"])
    mins_str = ", ".join(f"{x:.4f}f" for x in params["mins"])
    maxs_str = ", ".join(f"{x:.4f}f" for x in params["maxs"])
    
    header = f"""/**
 * Pre-trained Environmental Baseline Parameters
 * Auto-generated by train_anomaly_model.py
 */

#ifndef BASELINE_PARAMS_H
#define BASELINE_PARAMS_H

static const float PRETRAINED_MEANS[] = {{{means_str}}};
static const float PRETRAINED_STDS[]  = {{{stds_str}}};
static const float PRETRAINED_MINS[]  = {{{mins_str}}};
static const float PRETRAINED_MAXS[]  = {{{maxs_str}}};

#endif // BASELINE_PARAMS_H
"""
    with open(output_path, "w") as f:
        f.write(header)
        
    print(f"[TinyML] Exported C++ baseline header to {output_path}")


def main():
    print("=== Training TinyML Baseline Anomaly Model ===")
    data = generate_synthetic_environmental_data(5000)
    params = compute_baseline_params(data)
    
    print("Computed Baseline Parameters:")
    for i, (m, s) in enumerate(zip(params["means"], params["stds"])):
        print(f"  Channel {i}: mean={m:.2f}, std={s:.2f}")
        
    out_cpp = os.path.join(os.path.dirname(__file__), "models", "baseline_params.h")
    export_cpp_header(params, out_cpp)
    print("TinyML training complete!")


if __name__ == "__main__":
    main()
